{% set name = "spectrally" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spectrally-{{ version }}.tar.gz
  sha256: ae54d7c907bca717fb020150bdceb81d910e3475124d45ec91dbc1468ad1dab4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spectrally-version = spectrally.scripts.spectrallyversion:main
    - specrally-custom=spectrally.scripts.spectrallycustom:main
    - spectrally = spectrally.scripts.spectrally_bash:main

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy <2.0
    - scipy
    - matplotlib-base
    - pandas
    - requests
    - datastock >=0.0.41
    - bsplines2d >=0.0.16

test:
  imports:
    - spectrally
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/spectrally
  summary: A python library for generic spectrum fitting, using datastock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
