{% set name = "spectrally" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spectrally-{{ version }}.tar.gz
  sha256: f0557e9b35a7704aac73345cc5662d6f11e4eb6023e62a94adedc7837bbd7755

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spectrally-version = spectrally.scripts.spectrallyversion:main
    - specrally-custom=spectrally.scripts.spectrallycustom:main
    - spectrally = spectrally.scripts.spectrally_bash:main

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy <2.0
    - scipy
    - matplotlib-base
    - pandas
    - requests
    - bsplines2d >=0.0.16

test:
  imports:
    - spectrally
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/spectrally
  summary: A python library for generic spectrum fitting, using datastock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
