{% set name = "spectrally" %}
{% set version = "0.0.7" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spectrally-{{ version }}.tar.gz
  sha256: 44ebcd04c76fad8e6a9eb094d36f09bf88d4983a899cbcf20c4a926f1c3a5133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spectrally-version = spectrally.scripts.spectrallyversion:main
    - specrally-custom=spectrally.scripts.spectrallycustom:main
    - spectrally = spectrally.scripts.spectrally_bash:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - scipy
    - matplotlib-base
    - pandas
    - requests
    - datastock >=0.0.42
    - bsplines2d >=0.0.17

test:
  imports:
    - spectrally
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ToFuProject/spectrally
  summary: A python library for generic spectrum fitting, using datastock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
